# Google Toolbox for Mac, which is macOS-specific code needed for building
[google-toolbox-for-mac]
version = 3.0.0
url = https://github.com/google/google-toolbox-for-mac/archive/v%(version)s.tar.gz
download_filename = google-toolbox-for-mac-v%(version)s.tar.gz
strip_leading_dirs = google-toolbox-for-mac-%(version)s
sha512 = 18e1e8d91869f82c1b4582c60e191a6f946dd9958f1e1279d86259d45589fbceec636f75f939e96b6a85a2fa457d4df2e6b143b44d21feab21700309addca575
output_path = third_party/google_toolbox_for_mac/src

[sparkle]
version = 2.9.2
url = https://github.com/sparkle-project/Sparkle/archive/refs/tags/%(version)s.tar.gz
sha512 = a52c3ce998c48b70bf704270f0adf0b7fb523ad2e31bac59dcf34ea7a934d7d95c3ae7f551d7d92f8466fc36856e5408b01e35e5e48217e26480d4669e17f9af
strip_leading_dirs = Sparkle-%(version)s
download_filename = sparkle-v%(version)s.tar.gz
output_path = third_party/sparkle
